@host = http://localhost:5252

### Default 5-day forecast
GET {{host}}/api/v1/weather
Accept: application/json

### Custom 10-day forecast
GET {{host}}/api/v1/weather?days=10
Accept: application/json

### Invalid value
GET {{host}}/api/v1/weather?days=-3
Accept: application/json
